- name: "Ansible uri : GET fqdn object - {{ rule_item.fqdn }}"
  ansible.builtin.uri:
    url: "{{ cred_rama6_fortigate_url }}cmdb/firewall/address?vdom={{ rule.vdom }}&filter==fqdn=@{{ rule_item.fqdn }}"
    method: GET
    headers:
      Authorization: "Bearer {{ cred_rama6_fortigate_api_token }}"
    status_code: 200
    timeout: 60
    validate_certs: false
  register: existing_fqdn_address
  
- name: "Append fqdn object name into srcaddr"
  ansible.builtin.set_fact:
    srcaddr: "{{ srcaddr + [{'name': existing_fqdn_address.json.results[0].name}] }}"
  when: 
    - "'source' in action_tasks" 
    - existing_fqdn_address.json.results != []

- name: "Append fqdn object name into dstaddr"
  ansible.builtin.set_fact:
    dstaddr: "{{ dstaddr + [{'name': existing_fqdn_address.json.results[0].name}] }}"
  when: 
    - "'destination' in action_tasks" 
    - existing_fqdn_address.json.results != []

- name: "Ansible uri : POST create fqdn object - {{ rule_item.fqdn }}"
  ansible.builtin.uri:
    url: "{{ cred_rama6_fortigate_url }}cmdb/firewall/address?vdom={{ rule.vdom }}"
    method: POST
    headers:
      Authorization: "Bearer {{ cred_rama6_fortigate_api_token }}"
    body_format: json
    body:
      json:    
        name: "{{ rule_item.fqdn }}"
        type: "fqdn"
        fqdn: "{{ rule_item.fqdn }}"
    status_code: 200
    timeout: 60
    validate_certs: false
  register: new_fqdn_address_response
  when: 
    - existing_fqdn_address.json.results == []

- name: "Append new fqdn object name into srcaddr"
  ansible.builtin.set_fact:
    srcaddr: "{{ srcaddr + [{'name': rule_item.fqdn}] }}"
  when: 
    - "'source' in action_tasks" 
    - existing_fqdn_address.json.results == []
    - new_fqdn_address_response.status == 200

- name: "Append new fqdn object name into dstaddr"
  ansible.builtin.set_fact:
    dstaddr: "{{ dstaddr + [{'name': rule_item.fqdn}] }}"
  when: 
    - "'destination' in action_tasks" 
    - existing_fqdn_address.json.results == []
    - new_fqdn_address_response.status == 200

- name: "Stop workflow if failed to create fqdn object - {{ rule_item.fqdn }}"
  ansible.builtin.fail:
    msg: "Failed to create fqdn object - {{ rule_item.fqdn }}"
  when: 
    - existing_fqdn_address.json.results == []
    - new_fqdn_address_response.status != 200