- name: "Include tasks : retrive schedule"
  ansible.builtin.include_tasks:
    file: get_object_tasks/schedule.yml
  when: 
    - "'schedule' in action_tasks"
    - rule.firewall_rule.schedule.startDate != 'always'
    - rule.firewall_rule.schedule.endDate != 'always'

- name: "Include tasks : always schedule"
  ansible.builtin.include_tasks:
    file: get_object_tasks/always_schedule.yml
  when: 
    - "'schedule' in action_tasks"
    - rule.firewall_rule.schedule.startDate == 'always'
    - rule.firewall_rule.schedule.endDate == 'always'

- name: "Include tasks : retrive service"
  ansible.builtin.include_tasks:
    file: get_object_tasks/service.yml
  when: "'service' in action_tasks"