- name: "Ansible uri : GET DENY Rule"
  ansible.builtin.uri:
    url: "{{ cred_rama6_fortigate_url if rule.site == 'Rama6' else cred_pttn_fortigate_url }}cmdb/firewall/policy?vdom={{ rule.vdom }}&filter==action==deny"
    method: GET
    headers:
      Authorization: "Bearer {{ cred_rama6_fortigate_api_token if rule.site == 'Rama6' else cred_pttn_fortigate_api_token }}"
    status_code: 200
    timeout: 60
    validate_certs: false
  register: deny_rule_response

- name: "Set fact find deny rule in zone"
  ansible.builtin.set_fact:
    in_zone_deny_rule_id: "{{ deny_rule_response.json.results | selectattr('srcintf.0.name', 'equalto', firewall_rule.srcintf.0.name) | selectattr('dstintf.0.name', 'equalto', firewall_rule.dstintf.0.name) | selectattr('srcaddr.0.name', 'equalto', 'all') | selectattr('dstaddr.0.name', 'equalto', 'all') | list | first | default({}) }}"

